id: 1
ramProvisioner:
  availableRam: 1000
bwProvisioner:
  bw: 1000
storage: 1
peList:
  - id: 1
    peProvisioner:
      availableMips: 100
  - id: 2
    peProvisioner:
      availableMips: 100
  - id: 3
    peProvisioner:
      availableMips: 100
vmScheduler:
  peList:
    - id: 1
      peProvisioner:
        availableMips: 100
    - id: 2
      peProvisioner:
        availableMips: 100
    - id: 3
      peProvisioner:
        availableMips: 100