id: 0
ramProvisioner: 
  availableRam: 4096
bwProvisioner: 
  bw: 1000
storage: 1000000
peList:
  $type: template
  $count: 8
  $ids:
    - id
  $template:
    peProvisioner: 
      availableMips: 40
vmScheduler:
  $type: builtin
  $path: org.infrastructureProvider.policies.vm.VmSchedulerSpaceShared
  peList:
    $type: reference
    $path: ../peList