characteristics:
  $type: resource
  $user: LoadTest
  $path: DatacenterCharacteristicsTest.yaml
vmAllocationPolicy:
  list:
    $type: reference
    $path: ../characteristics.hostList # 同级需要在同一个子树上！
storageList: null
schedulingInterval: 1
location:
  $type: resource
  $user: LoadTest
  $path: LocationTest.yaml
geoCoverage:
  $type: resource
  $user: LoadTest
  $path: GeoCoverageTest.yaml
level: 1